### ISSUE TITLE
Error setting up platform.

### ISSUE THREAD

**Issue by djtimca** [slashback100/presence_simulation#1]
Looks like a great concept - trying to install and set up and getting:

Logger: homeassistant.setup
Source: custom_components/presence_simulation/__init__.py:20
First occurred: 14:46:05 (1 occurrences)
Last logged: 14:46:05

Error during setup of component presence_simulation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/presence_simulation/__init__.py", line 20, in async_setup
    return await async_mysetup(hass, config[DOMAIN].get("entity_id",[]), config[DOMAIN].get('delta', "7"))
KeyError: 'presence_simulation'

**Comment by slashback100** [comment]
What do you have in your configuration.yaml?
Does it work if you do not fill configuration.yaml and try to add the component through the UI?

**Comment by djtimca** [comment]
I configured through the UI

**Comment by slashback100** [comment]
Ok I reproduced the issue.
I fixed it by adding `presence_simulation:` in the configuration.yaml.
I try to fix that.

**Comment by slashback100** [comment]
Solved it.
Thanks for raising this issue.
