### ISSUE TITLE
Will devices in the group be triggered individually or all at once 

### ISSUE THREAD

**Issue by redlefloh** [slashback100/presence_simulation#105]
qq, will the devices in the presence simulation light group that one would add in the default configuration be treated individually or will they be triggered all at once with the group?
i.e. if the group light.presence_simulation_light_group includes light.livingroom, light.diningroom, and light.bedroom, will those lights all be triggered together at once or will the living room light trigger whenever the living room light was switched on and off x days ago and independently dining room and bed room will also be switched individually based on their previous behavior?
Thanks!

**Comment by slashback100** [comment]
The simulation will expand all groups into single entities. Which means that the simulation will simulate all entities independently, not as groups.
