### ISSUE TITLE
[Feature Request] Simulate lights only after sunset and before sunrise

### ISSUE THREAD

**Issue by bit-bat** [slashback100/presence_simulation#106]
Thank you for this wonderful repo!

I am planning to use this during my vacation, and thought of an enhancement. I am only using presence simulation for lights that can be seen from outside the house (rooms with windows to the front). Although when we are home, we use the lights in these rooms during daytime, they are barely visible from the outside during daytime. Simulating presence for these lights during daytime doesn't make much sense for my use case.

It would be great if presence simulation could be paused from dawn to dusk. In other words, I would want to run presence simulation only from sunset [+/- offset] to sunrise [+/- offset].

Thanks!

P.S. I will try to create a PR for this as I get some time.

**Comment by slashback100** [comment]
Hello,
Why don't you simply create an automation that will activate the simulation at sunset (+/- offset)  and disable it at sunrise (+/- offset) ?

**Comment by bit-bat** [comment]
Yeah, good idea. 
I guess I can use multiple triggers - empty house and sunrise/sunset.
Thanks
