### ISSUE TITLE
Ignore lights with "unavailable" state

### ISSUE THREAD

**Issue by hgregorian** [slashback100/presence_simulation#107]
Hi!  I'm enjoying this integration and would like to suggest a minor tweak.  It seems that the integration considers all historical state changes, including unavailable.  Would it be possible to simply ignore/skip over entities which have an unavailable state?

![image](https://github.com/slashback100/presence_simulation/assets/6110024/2d909042-3862-4fa9-99f8-1f6806d4cc81)

**Comment by slashback100** [comment]
Hello.
The `unavailable` are indeed gather in the historic, but they won't be processed. They will be ignored and you may see something like this `State in unavailable, do nothing` or this `State in neither on nor off (is unavailable), do nothing` in your log. 
I may though improve the process to avoid displaying them in the next event metadata

**Comment by slashback100** [comment]
Done : https://github.com/slashback100/presence_simulation/releases/tag/v3.3

**Comment by hgregorian** [comment]
Sorry to be a bother, but 3.3 was already released.  Commits related to this change are marked as 3.4, but this has not been tagged.

> Done : https://github.com/slashback100/presence_simulation/releases/tag/v3.3

**Comment by hgregorian** [comment]
Sorry to be a bother, but 3.3 was already released.  Commits related to this change are marked as 3.4, but this has not been tagged.

> Done : https://github.com/slashback100/presence_simulation/releases/tag/v3.3

**Comment by slashback100** [comment]
Yep sorry... error on my part. There you go 
https://github.com/slashback100/presence_simulation/releases/tag/v3.4
