### ISSUE TITLE
Light entity not accepted in UI config flow

### ISSUE THREAD

**Issue by kongo09** [slashback100/presence_simulation#11]
The UI config flow does not accept a simple light entity.

![image](https://user-images.githubusercontent.com/640121/118199311-160a6f80-b453-11eb-80da-20b9ddd63bfb.png)

**Comment by slashback100** [comment]
Could you test the workaround given in https://github.com/slashback100/presence_simulation/issues/6 please?

**Comment by kongo09** [comment]
Yes, that works. I feel the problem is with the way you use voluptuous to verify the input?
