### ISSUE TITLE
Help re event presence_simulation_change

### ISSUE THREAD

**Issue by Wright55** [slashback100/presence_simulation#118]
You advise
Each time the simulation calls a service (turn on a light, open a cover, ...), an event presence_simulation_change is fired. You can catch this event in an automation, to notify you for instance.
Would appreciate if you can help in setting this up.
I have a group with 11 lights listed.
I know how to set up basic automations but researching has not helped.

**Comment by slashback100** [comment]
Here is a simple example that will create a persistent notification :
```
alias: Test Simulation Event
trigger:
  - platform: event
    event_type: presence_simulation_change
action:
  - service: persistent_notification.create
    metadata: {}
    data:
      message: >-
        Simulation of the entity {{ trigger.event.data.entity_id }},  {{
        trigger.event.data.service }} called with following parameters: {{
        trigger.event.data.service_data }}
mode: single
```

**Comment by Wright55** [comment]
﻿Thank you for this, all makes sense, however does not appear to work.This is my slightly altered automationalias: Presence Simulation Event Testdescription: ""trigger:  - platform: event    event_type: presence_simulation_changeaction:  - service: notify.whatsapp    metadata: {}    data:      message: >-        Simulation of the entity {{ trigger.event.data.entity_id }},  {{        trigger.event.data.service }} called with following parameters: {{        trigger.event.data.service_data }}mode: singleMy automation to run PS works fine and I can also trigger using the switch manually, however whilst my lights do come on as expected the event automation does not trigger.Anything else I should be doing.GrahamSent from my iPad ProOn 14 Mar 2024, at 10:46, slashback100 ***@***.***> wrote:﻿
Here is a simple example that will create a persistent notification :
alias: Test Simulation Event
trigger:
  - platform: event
    event_type: presence_simulation_change
action:
  - service: persistent_notification.create
    metadata: {}
    data:
      message: >-
        Simulation of the entity {{ trigger.event.data.entity_id }},  {{
        trigger.event.data.service }} called with following parameters: {{
        trigger.event.data.service_data }}
mode: single

**Comment by Wright55** [comment]
alias: Presence Simulation Event Test
description: ""
trigger:
  - platform: event
    event_type: presence_simulation_change
action:
  - service: notify.whatsapp
    metadata: {}
    data:
      message: >-
        Simulation of the entity {{ trigger.event.data.entity_id }},  {{
        trigger.event.data.service }} called with following parameters: {{
        trigger.event.data.service_data }}
mode: single

**Comment by Wright55** [comment]
alias: Presence Simulation Event Test
description: ""
trigger:
  - platform: event
    event_type: presence_simulation_change
action:
  - service: notify.whatsapp
    metadata: {}
    data:
      message: >-
        Simulation of the entity {{ trigger.event.data.entity_id }},  {{
        trigger.event.data.service }} called with following parameters: {{
        trigger.event.data.service_data }}
mode: single
