### ISSUE TITLE
Feature Request - brightness options

### ISSUE THREAD

**Issue by patienttruth** [slashback100/presence_simulation#122]
I was wondering if it would be difficult to incorporate a range and offset for brightness while presence_simulation is running. The purpose being to reduce power consumption while still providing indication that someone may be present.

Thank you so much for the awesome integration!

**Comment by sdahbour** [comment]
This integration is fantastic.  Works perfectly and does everything right.  I agree that supporting brightness would make it perfect.  Instead of just turning on, turn it on at the brightness level at which the light was previously set.  Thanks again!

**Comment by henfri** [comment]
I was about to ask the same.
Brightness could bei Limited to a fixed value or multiplied by a Factor.

**Comment by henfri** [comment]
@slashback100 thanks for implementing brightness.

Are the Features requested Here (max brightness or scaling) also already implemented?

**Comment by slashback100** [comment]
In the release 4.11 (just released), you can configure a default percentage (1 -> 100) that will use for all the lights during the simulation.

**Comment by slashback100** [comment]
![image](https://github.com/user-attachments/assets/43f7c4df-0fa0-4593-8f8e-00848ad56d4b)

**Comment by patienttruth** [comment]
> ![image](https://private-user-images.githubusercontent.com/43109757/399480146-43f7c4df-0fa0-4593-8f8e-00848ad56d4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2ODYyNzEsIm5iZiI6MTczNTY4NTk3MSwicGF0aCI6Ii80MzEwOTc1Ny8zOTk0ODAxNDYtNDNmN2M0ZGYtMGZhMC00NTkzLThmOGUtMDA4NDhhZDU2ZDRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDIyNTkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNmFkODQ1ZmFlNDZmZmM2MGZiODBlNGRmYmY4MmE2NDJhMWJiMGM3YWVhYzVkOTI4NmM1ZDEzMTcwNmFlZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZbAhM9gj_1za3CXtQyjYdzO7_mpGdFtynNsuwtc1bnQ)

Thank you!

**Comment by sdahbour** [comment]
That’s great!  Thanks!

**Comment by henfri** [comment]
@slashback100 

Thanks again. However, I think it would be better to allow for:
- a fixed value (as you did)
- a factor (e.g. 50% of what the played-back/historical value was)
- a threshold (i.e. the historical value, but not more than 50%)

Would that be possible/would you be willing to enable that?

Best regards,
Hendrik

**Comment by hvorragend** [comment]
I'm not 100% sure. But exactly this information should not be available in the history, should it? Only the state and not the attributes are stored in the long term.
