### ISSUE TITLE
Setting data/options directly to update a config entry is deprecated

### ISSUE THREAD

**Issue by cupracer** [slashback100/presence_simulation#124]
Hi, I have just installed your integration for the first time and out of curiosity took a look at the HA log. I noticed the following warnings:

`2024-04-11 07:20:16.889 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'presence_simulation' sets "data" directly to update a config entry. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to use async_update_entry instead at custom_components/presence_simulation/__init__.py, line 456: entry.data = entry.options, please create a bug report at https://github.com/slashback100/presence_simulation/issues`

`2024-04-11 07:20:16.891 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'presence_simulation' sets "options" directly to update a config entry. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to use async_update_entry instead at custom_components/presence_simulation/__init__.py, line 457: entry.options = {}, please create a bug report at https://github.com/slashback100/presence_simulation/issues`

I don't know if you already know this topic, so I'm posting it here for your information.

**Comment by slashback100** [comment]
I saw it but didn't have an issue yet. Thanks :-)
