### ISSUE TITLE
Feature Request Option handel Device unavailable as Device Off

### ISSUE THREAD

**Issue by cyberoeze** [slashback100/presence_simulation#128]
Because Some Lights in my home are turned off by an physical button and therefore the device is not going in the Status off, it will be in go in the Status unavailable.

It would be nice if i have the option that the state device unavailable will be handeld as device off

**Comment by slashback100** [comment]
I added a switch in the configuration of the component "Consider unavailable as off", which should do what you want.
I didn't create a new release yet. Maybe you coud test the main version before I launch a release?

**Comment by cyberoeze** [comment]
i copied the code and create a dummy german translation to test it. I will test it as fast as possible

**Comment by cyberoeze** [comment]
Test was successfull, the only thing that i noticed are missing translations.
