### ISSUE TITLE
Next event date time shows time in the past

### ISSUE THREAD

**Issue by kongo09** [slashback100/presence_simulation#13]
The attribute next event date time shows a time in the past

![Screenshot_20210514-101733_Home Assistant](https://user-images.githubusercontent.com/640121/118248432-93aa9b80-b4a4-11eb-8195-1a9d1fa4185c.jpg)

**Comment by slashback100** [comment]
The next event datetime is display at GMT+00.00, I guess that explains it

**Comment by kongo09** [comment]
That is it, thanks. It's confusing, because the simulation start field shows a different format. Any way to make both the same?

**Comment by slashback100** [comment]
Done
