### ISSUE TITLE
hass.config_entries.async_forward_entry_setup is deprecated

### ISSUE THREAD

**Issue by candrea77** [slashback100/presence_simulation#137]
Calling hass.config_entries.async_forward_entry_setup is deprecated and will be removed in Home Assistant 2025.6. Instead, await hass.config_entries.async_forward_entry_setups as it can load multiple platforms at once and is more efficient since it does not require a separate import executor job for each platform.

https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups/

**Comment by gogades** [comment]
I see this is fixed in 4.10 (as per the manifest.json) but HACS is only showing me version 4.9 
<img width="348" alt="image" src="https://github.com/user-attachments/assets/0efc1e38-330f-48f7-bca0-1bcd56a74d74">

Is there something I should be doing to pickup the update?

**Comment by slashback100** [comment]
Nothing wrong, 4.10 is not released yet

**Comment by gogades** [comment]
Ok thanks.

**Comment by slashback100** [comment]
V4.10 released :-)
