### ISSUE TITLE
Question: History Offline as Off?

### ISSUE THREAD

**Issue by Mister-A** [slashback100/presence_simulation#140]
Apologies for raising as an issue but with discussions not available and me not able to locate a community support thread on https://community.home-assistant.io I couldn't think of a better place to ask. Please just close if inappropriate.

Just trying to understand if a light going offline in history will cause Presence Simulation to turn off the corresponding light?

Reason being, some of my smart lights are just wifi bulbs and in rooms where I don't have/it's not appripriate to have presence sensors to automate them inevitably my family tend to use the light switch and so bulbs get powered down rather then "switched off" from a smart home point of view and so the historic event for this is "Became unavailable".

I *do* want Presence Simulation to follow this power on/power off historical event as a light on/off to repeat. Will it?

(I'm going away tomorrow and doing last minute upgrading my "away" mode from my previous random script to Presence Sim and so am short on time to test and find the answer for myself!)

Thanks
Andrew

**Comment by slashback100** [comment]
Yes, unavailable is considered as off. Requested in #128

**Comment by Mister-A** [comment]
Many thanks!
