### ISSUE TITLE
Type when trying to rename the entity

### ISSUE THREAD

**Issue by Hichiro6** [slashback100/presence_simulation#146]
![image](https://github.com/user-attachments/assets/4ab4dccf-3ff6-40e6-a3bd-0ff81b6e53dd)

Repro ste:

Go in configure, try to rename the entities, the error message contains a typo "Swtich"

**Comment by slashback100** [comment]
Thanks. It has already been resolved in https://github.com/slashback100/presence_simulation/commit/9dc81216b521681cb597b8ad9d2c628e8892a5f2 (not yet released)
