### ISSUE TITLE
Support previous brightness

### ISSUE THREAD

**Issue by sdahbour** [slashback100/presence_simulation#147]
This integration is fantastic.  Works perfectly and does everything right.  Would it be possible  to support brightness?  Instead of turning on the light,  turn it on at the brightness level at which the light was previously set.  Thanks again!

**Comment by slashback100** [comment]
I use to work that way but doesn't anymore because of changes in the way HA store the states (it doesn't store brightness in the history anymore).
So #122 was requested. It is ongoing. 
--> I'm closing this one
