### ISSUE TITLE
no version key

### ISSUE THREAD

**Issue by fireport** [slashback100/presence_simulation#17]
In my home assistant log I found this entry
No 'version' key in the manifest file for custom integration 'presence_simulation'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'presence_simulation'
Please fix this.
Thank you

**Comment by fireport** [comment]
open for error

**Comment by slashback100** [comment]
The manifest does contain the version though...
https://github.com/slashback100/presence_simulation/blob/main/custom_components/presence_simulation/manifest.json

**Comment by slashback100** [comment]
Which version are you using?

**Comment by fireport** [comment]
I don't think that is the latest one (my files are much older than the ones in the repository)  but HACS doesn't notify me that a new version exists.

**Comment by fireport** [comment]
Problem solved. I force un update and the problem disappear.
Thank you
