### ISSUE TITLE
Error Toggling Presence Switch

### ISSUE THREAD

**Issue by obbers** [slashback100/presence_simulation#18]
In core-2021.5.5, this is what shows up in the log with 1 enitity configured via the gui with HACS install

Traceback (most recent call last):
  File "/config/custom_components/presence_simulation/__init__.py", line 221, in simulate_single_entity
    await update_entity(entity_id, state)
  File "/config/custom_components/presence_simulation/__init__.py", line 254, in update_entity
    await hass.services.async_call("light", "turn_"+state.state, service_data, blocking=False)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1428, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service light.turn_unavailable

**Comment by slashback100** [comment]
What's the entity_id you have set?
Are you sure it is a valid entity_id?
Could you show me what is its state in States screen (https://my.home-assistant.io/redirect/developer_states/)?

**Comment by obbers** [comment]
So it's just a lightbulb.  here's the current state of things:

min_mireds: 153
max_mireds: 370
supported_color_modes:
  - color_temp
color_mode: color_temp
brightness: 68
color_temp: 200
off_brightness: null
friendly_name: Bedroom2 Bulb 1
supported_features: 43



friendly_name: Presence Simulation
simulation_start: '2021-05-20T13:44:11.390073-05:00'
entity_id:
  - light.bedroom2bulb1
next_event_datetime: '20/05/2021 13:44:11'
next_entity_id: light.bedroom2bulb1
next_entity_state: unavailable


![image](https://user-images.githubusercontent.com/17300900/119034390-dd4b2880-b973-11eb-8cd0-7970b3709dc7.png)

**Comment by slashback100** [comment]
It's not clear to me what is the real entity_id of your bulb, is `light.bedroom2bulb1` correct ? It's not `light.bedroom2_bulb_1`? (since I see spaces in the friendly_name)

**Comment by slashback100** [comment]
I just release a new version that adds controls on the entities and on the entity states (if it is unknown for instance, skip the state during the simulation)
