### ISSUE TITLE
Switch platform never gets set up - needs to be in switch.py

### ISSUE THREAD

**Issue by djtimca** [slashback100/presence_simulation#2]
Getting error:

```
Logger: homeassistant.setup
Source: setup.py:280
First occurred: 11:05:30 (1 occurrences)
Last logged: 11:05:30

Unable to prepare setup for platform presence_simulation.switch: Platform not found (No module named 'custom_components.presence_simulation.switch').
```

I think you need to move the switch platform out of the `__init__.py` and into its own `switch.py` file for this to get set up correctly. There are lots of examples to look at in the Home Assistant components.

**Comment by slashback100** [comment]
I forgot to commit my `switch.py` :-p

**Comment by slashback100** [comment]
Thanks for noticing
