### ISSUE TITLE
Integration not available in HACS by default

### ISSUE THREAD

**Issue by whi-tw** [slashback100/presence_simulation#20]
Hi,

Unsure if this is just a me-problem, but after your advice the other day, I decided to go ahead and try HACS.

I was not able to find Presence Simulation after following the guide in this repo: I had to add this repo as a custom repository, and then it became available. Not sure if this is a problem upstream, but may be worth an NB in the readme.

Thanks!

**Comment by slashback100** [comment]
It has been added in HACS 7 days ago : https://github.com/hacs/default/pull/946
So I will close the ticket. It can be re-open if several users encountered the same issue
