### ISSUE TITLE
Error identifying entities

### ISSUE THREAD

**Issue by wormiedk** [slashback100/presence_simulation#21]
I get this error when trying to enable the extension. It has worked previously 

This error originated from a custom integration.

Logger: custom_components.presence_simulation
Source: custom_components/presence_simulation/__init__.py:161
Integration: Presence Simulation (documentation, issues) 
First occurred: 4 June 2021, 15:28:25 (4 occurrences) 
Last logged: 6:45:00

Error during identifing entities

**Comment by wormiedk** [comment]
I can see that a few lights included in the group are offline but I guess that should not be a problem?

**Comment by slashback100** [comment]
Please activate the debug level and send the log.
It should occur if you refer an entity that doesn't exist or a group that contains an entity that doesn't exist.

**Comment by slashback100** [comment]
Closing issue because of insufficient information given
