### ISSUE TITLE
FR: Only after sundown

### ISSUE THREAD

**Issue by wormiedk** [slashback100/presence_simulation#22]
I think presence simulation makes most sense when it is dark outside. It would be great if you could enable an option to only do the simulations while it is dark / sun is down

**Comment by ruddj** [comment]
Wouldn't this be best implemented in an Automation? 
Also if it is just playing back your existing usage it won't turn lights on during day unless you already had them on during day yourself.

**Comment by slashback100** [comment]
I agree with ruddj.
If you say that normally lights should not turn on if it is not the night, well you shouldn't have to turn it on the week before at the same hour. And if you did, it was for a good reason, so it makes also make sens to turn it on during the silmulation.
