### ISSUE TITLE
Presence simulation not loaded

### ISSUE THREAD

**Issue by proasnet** [slashback100/presence_simulation#23]
Hi, thank you for your work.
Some days ago, I found that integration of a presence simulation has icon Not Loaded. I was remove it and I trying load again,
I used a case 2 as install, I have a directory with PS. Bud in integrations and adding a new integration, a Presence Simulation is not found. Have you any idea?
Thank you.

**Comment by slashback100** [comment]
Any info in the logs?
Is the integration in the correct directory? i.e do you have this file: `~/.homeassistant/custom_components/presence_simulation/__init__.py`?

**Comment by proasnet** [comment]
Hi,
I have not a logs now, because integration is not exist in my integrations
and is not in a integrations repository. Is not possible add it to
integrations.
Directory is correct. It was created automaticaly by instalation
(custom_compom_ponents/presence_simulation)
Thanks

út 15. 6. 2021 v 11:26 odesílatel slashback100 ***@***.***>
napsal:

**Comment by slashback100** [comment]
@estoyarto , what version of HA are you using?
 The path of the module `history`changed some months ago and the adaptation was made in this component [in this commit](https://github.com/slashback100/presence_simulation/commit/5f1e0805889601878411ab07df126e4e6b1153d8#diff-917463c16303bb959767910749f424d88cf3de12e5b3c5677108977dc41774af)

**Comment by slashback100** [comment]
Closed due to missing information
