### ISSUE TITLE
Timezone error when turning on simulation entity

### ISSUE THREAD

**Issue by MrUkleja** [slashback100/presence_simulation#24]
Hi,

I'm getting this error when turning on simulation via entity switch.

`Logger: homeassistant.core
Source: custom_components/presence_simulation/__init__.py:168
Integration: Presence Simulation (documentation, issues)
First occurred: 19:52:37 (3 occurrences)
Last logged: 20:14:28

Error executing service: <ServiceCall presence_simulation.start (c:07ab2a3a10772c7893735d74cca3ce7a)>
Error executing service: <ServiceCall presence_simulation.start (c:442dcc99a7b3dd82bf4f59f05d1af13e)>
Error executing service: <ServiceCall presence_simulation.start (c:cedbcc7653a37f0a75b2d4e629d056ae)>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1507, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/presence_simulation/__init__.py", line 168, in handle_presence_simulation
    await entity.set_start_datetime(datetime.now(hass.config.time_zone))
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'
`

**Comment by MrUkleja** [comment]
I have time zone set via UI. It's Europe/Warsaw

**Comment by MrUkleja** [comment]
Tried setting it via configuration.yaml, but that didn't help

**Comment by slashback100** [comment]
Fixed in v1.3

**Comment by MrUkleja** [comment]
Started without errors. That you 👍
