### ISSUE TITLE
Exception while trying to convert utc to local time

### ISSUE THREAD

**Issue by henriklund** [slashback100/presence_simulation#26]
Starting presence simulation will show following error in the home-assistant.log

Exception while trying to convert utc to local time: tzinfo argument must be None or of a tzinfo subclass, not type 'str'

It appears as if the following line in switch.py is causing the trouble.

`self.attr["next_event_datetime"] = self.attr["next_event_datetime"].astimezone(self.hass.config.time_zone).strftime("%d/%m/%Y %H:%M:%S")`

**Comment by slashback100** [comment]
It should not cause any trouble though

**Comment by bob-tm** [comment]
I fix it like this:
`import pytz
 self.attr["next_event_datetime"] = self.attr["next_event_datetime"].astimezone(pytz.timezone(self.hass.config.time_zone)).strftime("%d/%m/%Y %H:%M:%S")`

**Comment by henriklund** [comment]
> It should not cause any trouble though

Ok. However, it is kind of a drag to get the log filled with this error (pops up every 5 secs

**Comment by henriklund** [comment]
> I fix it like this:
> `import pytz
> 
> self.attr["next_event_datetime"] = self.attr["next_event_datetime"].astimezone(pytz.timezone(self.hass.config.time_zone)).strftime("%d/%m/%Y %H:%M:%S")`

Yearh, I can see the same effect here. Thanks!

**Comment by bob-tm** [comment]
> It should not cause any trouble though
please add fix to next release. Errors each 5 sec in log are annoying.

**Comment by slashback100** [comment]
Fixed in v1.4
