### ISSUE TITLE
Support multiple simulations with different groups?

### ISSUE THREAD

**Issue by andyboeh** [slashback100/presence_simulation#27]
It seems to be possible to add the presence simulation integration twice and configure the integrations with different groups of lights. However, I can't seem to find a way to switch on a specific presence simulation, as only one switch and one service are created.

It would be nice if I could toggle presence simulation just for a part of my house.

Is this use-case supported at all?

**Comment by ruddj** [comment]
If you use presence_simulation.start to start it you can specify the group you want to use. Just create a template switch or automation that starts it with your chosen groups.
From [manual ](https://github.com/slashback100/presence_simulation#start-the-simulation)

**Comment by andyboeh** [comment]
Yeah, I saw that, but if I read the manual correctly, then it's still not possible to have two completely independent simulations: 
  - The `presence_simulation.stop` command does not have any parameter, so it stops any running simulation
  - What happens if I start it twice with different groups (I'm not at home right now to test it)?

**Comment by slashback100** [comment]
This is not a supported feature.

**Comment by andyboeh** [comment]
> This is not a supported feature.

OK - Any plans on supporting it or any hints on how to add this feature?

**Comment by slashback100** [comment]
I don't see any 'workaround' no.
I personally don't really see the added value of running 2 simulations at the same time. Running a single simulation on the union of the groups should produce the same result, no?

**Comment by andyboeh** [comment]
My goal is the following: In my house, we have two separate apartments (my parents and me) but just one Home Assistant for the entire house. I would like to give each apartment control over the simulation.

**Comment by slashback100** [comment]
@andyboeh, Just created a branch manage_multiple_switches with this feature. Don't know if you can test it, in particular the migration from old to new version.
Feature is developed in #95

**Comment by andyboeh** [comment]
Sorry no, I don't use this component any more.
