### ISSUE TITLE
Deprecated function called

### ISSUE THREAD

**Issue by henriklund** [slashback100/presence_simulation#28]
I noted following showing up in the log whenever presence_simulation.start is called.

WARNING (MainThread) [homeassistant.components.history] get_significant_states was called from presence_simulation, this is a deprecated function. Use homeassistant.components.recorder.history.get_significant_states instead, please report this to the maintainer of presence_simulation

**Comment by slashback100** [comment]
Thanks for noticing. I'll fix it
