### ISSUE TITLE
Presence simulation does not show in integration 

### ISSUE THREAD

**Issue by kasperkc87** [slashback100/presence_simulation#30]
Hi

I have tried to add this component with HACS, the files are added fine, and I can see in the logs that the component is being loaded. 

But when I follow the next steps (Go to UI and add) I cannot see the component ? 

I am running HA version 2021.7.2

![image](https://user-images.githubusercontent.com/69757958/125904660-81c8baf7-e024-4678-96b3-5b81f5d20b18.png)

**Comment by fuatakgun** [comment]
This is usually a cache issue, try with some other browser or clear your session cache in browser.
