### ISSUE TITLE
Question: Will it handle media players?

### ISSUE THREAD

**Issue by fribse** [slashback100/presence_simulation#31]
One of the true indicators that people are home is a TV running, it would be great if it could set those states as well, so, does it support that as well?

**Comment by slashback100** [comment]
If the TV integration switches the TV on & off through the services `homeassistant.turn_on` and  `homeassistant.turn_off`, yes. But only to turn it on/off.

**Comment by hillbicks** [comment]
I was asking myself the same question just now, would be nice to turn on the mediaplayer in the kitchen as well....

But I get why you want to limit it on/off states. There is a workaround though. Build a new automation: 
Trigger: MediaPlayer_X turned on
Condition: switch.presence_simulation = on
Action: Play whatever media on MediaPlayer_X

Music will stop automatically, when presence simulation turns off MediaPlayer_X.

**Comment by slashback100** [comment]
I just added the support for media_player.
It calls `media_player.media_play` if the state is `playing`.
It calls `media_player.media_stop` if the state is `stop`, `paused` or `idle`.
