### ISSUE TITLE
Adding a kind of random toggle

### ISSUE THREAD

**Issue by hvorragend** [slashback100/presence_simulation#32]
Is it possible to add a kind of random toggle the the lights?

A "presence simulation" with an additional feature to random turning lights on or off would be great. 

Because there could be long off-times in the 
meanwhile re-playing the recorded history. 

Perhaps similar the Node Reds "presence-faker". 

What do you think?

**Comment by fantastrick** [comment]
That would be amazing!

**Comment by pannal** [comment]
Wouldn't it be possible to approach something kind of similar to this, by adding a "variance" factor?

Looking at the code I'd say [this would be a good place](https://github.com/slashback100/presence_simulation/blob/main/custom_components/presence_simulation/__init__.py#L246) to add or substract a random range of seconds from the event.

The issue might be overlaps, though. Not sure if it'd be that bad.

**Comment by slashback100** [comment]
Fixed in version 1.11
https://github.com/slashback100/presence_simulation/releases/tag/v1.11

**Comment by hvorragend** [comment]
Thank you very much. Nice feature. 

I actually thought more of a simulation mode that you can optionally activate.
