### ISSUE TITLE
Connected switches with rules stuck in infinite loop

### ISSUE THREAD

**Issue by SkeLLLa** [slashback100/presence_simulation#36]
Hi. I have two switches with tasmota firmware. One switch is "virtual" and it has rule defined in it that switches toggle on other switch.

E.g.

When Switch A is turned on, then it issues MQTT command that toggles Switch B as well. And vise versa.

When I add one of switches to group controlled by presence simulation. and it is toggled on by presence simulation it starts infinite loop of switching on and off. And it can't be stopped without rebooting HA instance.

Is there any way to debug presence simulator in order to understand what happens in this case in order to provide some more valuable steps of reproduce? Or any other debugging tips will be helpful.

That behavior is observed on 1.4 version.

**Comment by slashback100** [comment]
I don't really understand how your configuration can work without turning in a infinite loop in a non simulation mode :-)
You can set the debug log level for all your HA or just this module, and add log in your local installation if you need mode log info.
