### ISSUE TITLE
Beta 2021.12.0b0 Error

### ISSUE THREAD

**Issue by Wibias** [slashback100/presence_simulation#38]
Entity switch.presence_simulation (<class 'custom_components.presence_simulation.switch.PresenceSimulationSwitch'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by Wibias** [comment]
Entity sensor.blitzortung_lightning_distance (<class 'custom_components.blitzortung.sensor.DistanceSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.blitzortung_lightning_azimuth (<class 'custom_components.blitzortung.sensor.AzimuthSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.blitzortung_lightning_counter (<class 'custom_components.blitzortung.sensor.CounterSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by slashback100** [comment]
Fix by commit https://github.com/slashback100/presence_simulation/commit/d38acf48d25069cf3034f7f57958bb307fc5fbfb
