### ISSUE TITLE
Italian translation =)

### ISSUE THREAD

**Issue by carloda** [slashback100/presence_simulation#39]
[it .json.txt](https://github.com/slashback100/presence_simulation/files/7833710/it.json.txt)

Hi, I translated into Italian how can I make it work?

thank you =)

**Comment by slashback100** [comment]
Thanks to you :-) You can fork the repository, commit and create a pull request so I can integrate it in this repo.
Or if you want, I can just commit it on my own?

**Comment by carloda** [comment]
> 

Hello, can you please do it? Thank you =)

**Comment by slashback100** [comment]
It is commited and released in v1.7.
Thanks :-)
