### ISSUE TITLE
Enhancement request: Handle Blinds

### ISSUE THREAD

**Issue by fribse** [slashback100/presence_simulation#42]
It's all very nice with the lights turning on and off, but it would be extra 'preventive' if the blinds were also handled.
They can be handled much in the same way as regular lights.

**Comment by slashback100** [comment]
I your blinds are represented has `cover`, it should be managed. Did you try it?

**Comment by fribse** [comment]
They are cover.* entities, I tried a setup in november, and that didn't work, it showed errors in the log. Has it changed since then?
I will find some time to test it again during the weekend to see if it works now.

**Comment by slashback100** [comment]
No it didn't change since november. But if you have some logs, please share it so I can try to fix it.

Thanks

**Comment by slashback100** [comment]
@fribse, did you have the chance to test it?

**Comment by fribse** [comment]
Hi @slashback100 
I've tried a few times, but I can't even get it to turn on now.
What on earth is going on?
I'm trying to use the switch.presence_simulation, and I've set the group.presence_simulation.
The group is defined like this:
presence_simulator:
  name: All entities for presence simulator
  entities:
    - light.all_commonareas
    - light.all_adrian
    - light.all_bedroom
    - light.all_office
    - cover.bedroom_blind
    - cover.livingroom_blind_big
    - cover.livingroom_small_window_blind
    - cover.office_window_blind

**Comment by slashback100** [comment]
In #52 you say you successful launch it, correct? Maybe you have then some logs for me?

**Comment by slashback100** [comment]
I just tried with v2.2 with a cover and it did work.
Please reopen/create a new issue with the log if you still have the problem.
Thanks
