### ISSUE TITLE
Updating presence_simulation switch took longer than the scheduled update interval

### ISSUE THREAD

**Issue by snowmangh** [slashback100/presence_simulation#48]
I installed and configured the "presence_simulation" add-on successfully as per documentation. If this add-on works as expected, it will remove the complexity of creating my own simulation. Great work. Kudos to the developers. 

![image](https://user-images.githubusercontent.com/90811206/156777094-75249bd0-9aaf-4b84-b433-ea9ce2bc16ce.png)

I am getting a warning and not sure what it relates to. 

What is the _scheduled update interval_? Is it the _Refresh interval (in seconds)_? I am tempted to say yes but thought I'd get a clarification and what action I should take if any.  Thanks

Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:719 
Integration: Switch ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22)) 
First occurred: 00:58:26 (1 occurrences) 
Last logged: 00:58:26
**Updating presence_simulation switch took longer than the scheduled update interval 0:00:05**

**Comment by slashback100** [comment]
This warning is triggered by HA when an action is taking more time than expected.
Here apparently, switching the presence_simulation (to `on` I guess?) took more than 5 seconds, which is apparently considered as a long time for HA.  
When turning the switch to `on`, it calls the service `presence_simulation.start`, which will get the history of all your lights in the DB and then launch a process for each light. This could take some time, depending on what your machine is busy with, on the number of light, on the number of days you simulation runs on, on the performance of your machine and DB...
In any way, this is just a warning.

**Comment by snowmangh** [comment]
@[slashback100](https://github.com/slashback100) Thanks for the fast response and explanation. Much appreciated.
