### ISSUE TITLE
Cannot add integration

### ISSUE THREAD

**Issue by ulfendk** [slashback100/presence_simulation#5]
Hi, this project is exactly what I have been looking for.  However, I can't seem to get it to work on my Hass OS  on Intel NUC running the latest stable of everything with MariaDB as the recorder backend?

The component is found (HA adds a warning to the log about untested component), but I cannot add the integration (not listed in the search for integrations).

Any clues?

Thank you.  I like what I see - I just wish it would work for me :)

**Comment by slashback100** [comment]
I just tried from a blank homeassistant installation and didn't get the issue. 
So you cloned the repository, restarted HA and can't find the integration in the integration page, right?
Could you extract everything concerning presence_simulation in your log please?

**Comment by ulfendk** [comment]
Sorry - I have been a little busy the past few days.

It turned out I had an issue with my recorder setup as well (kept getting constraint violations).  Got that fixed and re-installed the component.  Now I have it show up in integrations 👍

I look forward to exploring this :)

**Comment by slashback100** [comment]
👍
