### ISSUE TITLE
Tested first time and one question came

### ISSUE THREAD

**Issue by zigomatichub** [slashback100/presence_simulation#50]
Hello Slashback100, I'm very happy with your presence solution. It works great. Thank you for this awesome solution

My questions:

If I select 1 day for delta in configuration and I activate the presence switch during 2 days,  you mention, it will restart from the same delta period. 
Thus, the second day, presence will take the day -1 (which is in fact a copy of the day -2 due to the presence activation the day before), correct ?

If I'm putting 2 days in delta and activate presence for a week, then after 2 days, I will be also in a cycle of 2 days ?  Supposed answer is yes

I think to create one specific group of lights for presence. This group need to be part of the record db ? 
I'm asking this because I need to leave soon and it's not present today :)

Regards,
Zigomatic

**Comment by slashback100** [comment]
> Thus, the second day, presence will take the day -1 (which is in fact a copy of the day -2 due to the presence activation the day before), correct ?

Yes 
> If I'm putting 2 days in delta and activate presence for a week, then after 2 days, I will be also in a cycle of 2 days ? Supposed answer is yes

Yes

> I think to create one specific group of lights for presence. This group need to be part of the record db ?

Not the group but the lights in the groups should be

**Comment by zigomatichub** [comment]
Perfect,  thank you for your fast answer.
