### ISSUE TITLE
Feature Request: multiple istances

### ISSUE THREAD

**Issue by dapuzz** [slashback100/presence_simulation#55]
Hello
Is it possible to have multiple istances of precence simulator? In my use case I will bind to two different groups of lights.

Thank you
Bye

**Comment by slashback100** [comment]
No it is not possible.
Why don't you create a group that contains your 2 groups  of lights?

**Comment by dapuzz** [comment]
I wonder to turn on simulation only for one specific group, and may be the possibility to have different settings for each one.
May be this is just an idea for a feature request :-)

**Comment by slashback100** [comment]
Yes, it would be a new feature :-)
