### ISSUE TITLE
Presence simulation just stopped working

### ISSUE THREAD

**Issue by spudje** [slashback100/presence_simulation#56]
I'm running on Hass 2022.3.8, reverted back from 2022.4.x since it failed to upgrade MariaDB.
HACS is version 1.24.5

Everything worked fine after this rollback.

However today I noticed it stopped working with this error message:

Setup failed for custom integration presence_simulation: Unable to import component: cannot import name 'get_instance' from 'homeassistant.components.recorder' (/usr/src/homeassistant/homeassistant/components/recorder/__init__.py)

I have no clue whatsoever what is happening here. Help very much appreciated.

**Comment by slashback100** [comment]
Could you try with an earlier version of this custom component?
