### ISSUE TITLE
Error on newest Home-Assistant Dev Version 2022.7.0.dev

### ISSUE THREAD

**Issue by Wibias** [slashback100/presence_simulation#59]
Here is the log

` Setup failed for custom integration presence_simulation: Unable to import component: cannot import name 'States' from 'homeassistant.components.recorder.models' (/usr/src/homeassistant/homeassistant/components/recorder/models.py) `

**Comment by BigWebstas** [comment]
+1 im getting the same issue

**Comment by slashback100** [comment]
Fixed in v2.0.

**Comment by slashback100** [comment]
I guess you are using an earlier version than 2022.7.
v2.0 should only be used with 2022.7 and more (it is written in the description of the version).
Please go back to a v1.x version

**Comment by pannal** [comment]
Oh I misread. I'm on 2022.6.7, not 2022.7. Sorry!

**Comment by slashback100** [comment]
No problem. I found a way to make it compatible with old **and** new version of HA -> 2.1 published
