### ISSUE TITLE
"user input malformed"

### ISSUE THREAD

**Issue by finity69x2** [slashback100/presence_simulation#6]
I get the following every time I try to set up the integration thru the ui:

![ex1](https://user-images.githubusercontent.com/32221243/111883462-f21a3880-8991-11eb-9f54-c91918f669a5.gif)

Any suggestions?

**Comment by ufulu** [comment]
Have you tried it wihtout the group prefix?

**Comment by finity69x2** [comment]
using it without "group" resulted in the same thing.

I then reduced the delta to 5 and it worked.

but I have my recorder purge to 7 so I'm not sure where the issue was.

Closing now.

**Comment by ruddj** [comment]
> I then reduced the delta to 5 and it worked.

Thanks for posting your solution. I was having the same issue and changing delta to 5 allowed me to add the integration.

**Comment by kongo09** [comment]
You can actually change the `7` to a `7` and it will work. Nothing to do with the number but with the type. Maybe the code should verify the input as `int` and not as `str`?
