### ISSUE TITLE
Presence simulation stops with invalid entities

### ISSUE THREAD

**Issue by msm8811** [slashback100/presence_simulation#60]
When I trigger the simulation to start, I always get this error:  

Logger: custom_components.presence_simulation
Source: custom_components/presence_simulation/__init__.py:182
Integration: Presence Simulation ([documentation](https://github.com/slashback100/presence_simulation), [issues](https://github.com/slashback100/presence_simulation/issues))
First occurred: June 14, 2022, 8:17:47 AM (4 occurrences)
Last logged: 10:18:11 PM

Error during identifing entities, no valid entities has been found

I have tried making groups with the new groups helper, and it fails with this error. If I take the 30 or so lights and put them all on the entities list (separated by commas) during configuration, I get this error too.   This is all with 2022.6.6.

**Comment by slashback100** [comment]
Could you set the error level to debug, activate the simulation and send me the log please?

**Comment by slashback100** [comment]
Well that's strange...
The code is the following:
```
if hass.states.get(entity) is None:
    _LOGGER.error("Error when trying to identify entity %s, it seems it doesn't exist. Continuing without this entity", entity)
```
It this error is raised, it means the entity is not found in `hass.states`, which, as far as I know, is only supposed to happen if the entity doesn't exist...

**Comment by slashback100** [comment]
The `get` method of the `hass.states`  object :
```
    def get(self, entity_id: str) -> State | None:
        """Retrieve state of entity_id or None if not found.

        Async friendly.
        """
        return self._states.get(entity_id.lower())
```

**Comment by slashback100** [comment]
So if you type 
```
{{ states.light.bridge_bridge_wall_wash.state }}
{{ states('light.bridge_bridge_wall_wash') }}
```
in `Template` screen, what do you get?

**Comment by msm8811** [comment]
Thanks for working this.

When I type this into the templates screen,  I get 

off
off


in the results window.

**Comment by msm8811** [comment]
Did you fix something in this release from yesterday (v2.1) ?  The integration seems to not be throwing  errors as before when activated.  I have a light group and individual lights work.  However, if I have multiple entities on the UI based config, light light.lights_ps, and cover.covers_ps, it fails aagin.

How are you supposed to add multiple entities on the configuration UI?  Multiple entities separated by a comma?

**Comment by slashback100** [comment]
Nop, didn't change anything concerning your issue...
If you want to add several entities, you have to create group.

**Comment by msm8811** [comment]
Sorry, I don't understand the limitation.  You can't create a group with both covers and lights, or switches and lights - they all have to be in the same domain.  If I want to have both covers, lights, etc.. all be simulated, don't you have to be able to add multiple entities in the configuration?

**Comment by slashback100** [comment]
Hmm ok I understand. Actually I'm using groups that are apparently '[old fashion](https://www.home-assistant.io/integrations/group/#old-style-groups)` that allows to group entities from different domains... And that is not possible anymore.
I will then think about something to allow that...

**Comment by slashback100** [comment]
#62 created

**Comment by slashback100** [comment]
Support for multiple entities added in [v2.2](https://github.com/slashback100/presence_simulation/releases/tag/v2.2)

**Comment by msm8811** [comment]
This seems to work fine.  Thanks for the fix!
