### ISSUE TITLE
Cannot make the presence simulation work

### ISSUE THREAD

**Issue by ThomasGNielsen** [slashback100/presence_simulation#65]
Hi 
Home Assistant version 2022.7.7
Presence simulation version 2.2

I am new to HA. 
I cannot make the app work. I think is is something with the menu “Entity or groups of entities”. I am not sure what to write. I have made a group of lights and copied the make to the menu. However, nothing happens. No errors or nothing. And no lights are turned on. 
wWhat to do?

**Comment by slashback100** [comment]
Is the switch created?
Could you set the log to debug and try again? (procedure [here](https://github.com/slashback100/presence_simulation/issues/60#issuecomment-1171174701))

**Comment by ThomasGNielsen** [comment]
Thanks for your swift reply. I have no idea on how to set the log to debug. Where do I insert the code...?

**Comment by slashback100** [comment]
The service to change the log level needs to be called from [here](https://my.home-assistant.io/redirect/developer_services/).

Yes I guess that if a light is turning on, it is working :-) 
FYI you can take a look in [this screen](https://my.home-assistant.io/redirect/developer_states/) the attributes of the entity `switch.presence_simulation` when the simulation is launched, it will give you info about what it is doing and on which and when next light will be turned on/off.
