### ISSUE TITLE
Not listed in integrations

### ISSUE THREAD

**Issue by proasnet** [slashback100/presence_simulation#68]
Hello, I tried instal your integration Presence Simulator, The second git method, nothing, next I choosed a HACS method, is installed, HA restarted. In the next step, I trying add an integration, but Presence Simulation is not in a list of integrations. Something is wrong, but I dont know what...
I have a last version of a core and HACS.

**Comment by snyfear** [comment]
Same problem for me

**Comment by macrouch** [comment]
I was lost on this for a while too, the I saw the "Explore and Download Repositories" button on the HACS integrations page 
<img width="933" alt="Screen Shot 2022-10-27 at 8 59 02 PM" src="https://user-images.githubusercontent.com/171388/198427068-4035fbec-c08c-413d-a14d-b135f8f4d93a.png">
<img width="559" alt="Screen Shot 2022-10-27 at 8 59 10 PM" src="https://user-images.githubusercontent.com/171388/198427170-3f3ec96d-8bc0-41ad-8440-0bed21237554.png">
