### ISSUE TITLE
Question about using light groups

### ISSUE THREAD

**Issue by GussyH** [slashback100/presence_simulation#69]
Hi,

This integration is great! One question though - the docs show using an old-style group (group.xxxx) however what happens if I want to create a light group using the new group system? These show in the UI as light.xxx and look like a normal light. If I create that and use it in the configuration, does the simulation still look at the history of the individual entities in the group?

I'm sure it's a yes, but wanted to check :)

**Comment by slashback100** [comment]
Hello.
Yes the component will work with new style group as it does with old style groups.
