### ISSUE TITLE
Question: Is it possible to simulate cover positions?

### ISSUE THREAD

**Issue by aguedob** [slashback100/presence_simulation#7]

**Comment by slashback100** [comment]
Actually the code is made to support it, but I never had the chance to test it.

**Comment by slashback100** [comment]
Apparently the code is commented. So it won't work.
I can try to implement that.

**Comment by slashback100** [comment]
I uncommented the code.
I tested the open & close and it does work. 
I don't use position or tilt position so I can't test it.
