### ISSUE TITLE
Question - can't verify it's working, and helper groups

### ISSUE THREAD

**Issue by bf8392** [slashback100/presence_simulation#71]
Hi =) I just tested your integration, and I can't verify that it's actaully working...how can I do that? What I did:

1) Created a group under "helper - create group - switches - choose the entities
2) Setet up presence simulation integration according to manual
3) turned on (which it did without error). set it up to check every 10 seconds, switched the light manually -> nothing happened

Am I doing something wrong?

**Comment by slashback100** [comment]
You should not switch it manually. It wont't do nothing.
To check that the simulation works, look at the attributes of the `switch.presence_simulation`

**Comment by bf8392** [comment]
So when I switch manually, it won't switch back after the seconds checking to it's historical state? Sorry the question but what do you mean by "look at the attributes". (Restoring previous state works when I turn on the switch.presencesimulation over ui)

**Comment by slashback100** [comment]
What have you set for the attribute 'delta'? By default, it is 7 days. So it means that if you switch manually your light now, it is only in 7 days from now that the simulation will switch it.
The refresh interval parameter (if that's what you're actually talking about) is the time the simulation waits before re-checking whether a device should be switched, it is a technical parameter that doesn't affect the behavior.

**Comment by slashback100** [comment]
When I'm talking about looking, I'm talking about going in [here ](https://my.home-assistant.io/redirect/developer_states/), and look at the attributes column for the `switch.presence_simulation` entity

**Comment by bf8392** [comment]
So when I turn the presence simulation on, it doesn't repeat the historic state, it just records it from then on? I'm sorry I don't get it....I thought it works the following -> When I turn it on, the integration looks for historic light switches, 7 days before today, and then repeats them, to simulate someone is at home...

**Comment by bf8392** [comment]
```entity_id:
  - light.lumiere_dans_la_salle_a_manger
friendly_name: presence_simulation_scene

**Comment by bf8392** [comment]
'''
friendly_name: Presence Simulation
restore_states: true
random: 0
simulation_start: 2022-08-23T14:13:39.896420+02:00
entity_id: light.lumiere_dans_la_salle_a_manger
delta: 7
next_event_datetime: 30/08/2022 13:43:31
next_entity_id: light.lumiere_dans_la_salle_a_manger
next_entity_state: on

**Comment by bf8392** [comment]
? but to that time 7 weeks before the light was off...so I thought as soon as the presence eimualtion detects that the light is on, but was off 7 days ago, it will turn it off again...

**Comment by bf8392** [comment]
AHHHHH Okay I see =) Great thanks for the clarification =). Do you think it would be possible that the presence simulation is seeing it in future updates? =)

**Comment by bf8392** [comment]
what group should I use? I tried it with switch, but it doesn't seem to work...

**Comment by slashback100** [comment]
> Do you think it would be possible that the presence simulation is seeing it in future updates? =)

Not planned no 😃 

> what group should I use?

Should work with switches group, But in your example you are testing with a light, so I'd suggest a lights group.

**Comment by bf8392** [comment]
As soon as I try it with a group, or two lights, it doesn't switch anymore =(

**Comment by bf8392** [comment]
I seperate the entites by comma, and I use helper group switch...both doesn't seem to switch...

**Comment by bf8392** [comment]
When I first switch on the presence simulation, does it actualize the state?

**Comment by bf8392** [comment]
I left presence simulation on, and it doesn't do anything for me :-( is it possible that it has something to do with z-wave? The states are stored correctly in history, and when I switch off the switch.presence 
, It restores the state...

**Comment by bf8392** [comment]
I tested tonight it was perfectly! :-) great great thanks for your help!
