### ISSUE TITLE
Question: Hue light temperature changes

### ISSUE THREAD

**Issue by gebla** [slashback100/presence_simulation#75]
I noticed that some Hue lights have different light temperature after running the simulation. Is the light temperature somehow included in the history playback? Normally the temperature does not change when switching on.

**Comment by ValShaped** [comment]
Presence Simulation only knows about `color_rgb`, and doesn't check history for `color_temp`. I'm working on a PR right now to support every Home Assistant color mode

**Comment by gebla** [comment]
Thanks for the reply!
