### ISSUE TITLE
Last HA version and HACS??

### ISSUE THREAD

**Issue by gjelsoe** [slashback100/presence_simulation#8]
Hi,

Will this run on the last version of HA (2021.4.6) and will your intergration be update to work with last HACS version?

**Comment by slashback100** [comment]
Yes it should run with last version of HA.
This integration is not in HACS so I don't really understand your question.

**Comment by gjelsoe** [comment]
Could it be made to work with HACS ?

**Comment by kongo09** [comment]
There is a fork that provides the changes to install it as a custom component in HACS. However, when I do that, I cannot add it as integration, so something still seems to be wrong.

**Comment by kongo09** [comment]
Pardon my ignorance, @gjelsoe, this is your fork. And after I did a second reboot of HA, I was also able to select this component from the integrations configuration as described. Why don't you do a PR?

**Comment by gjelsoe** [comment]
> Pardon my ignorance, @gjelsoe, this is your fork. And after I did a second reboot of HA, I was also able to select this component from the integrations configuration as described. Why don't you do a PR?

Just made it for testing, but haven't come to that part yet :)

**Comment by slashback100** [comment]
I modified the structure of the repo to allow it to be added in hacs.
Next step is to add the icon/logo in the brands home assistant project, waiting for a review: 
https://github.com/home-assistant/brands/pull/2575

**Comment by gjelsoe** [comment]
> I modified the structure of the repo to allow it to be added in hacs.
> Next step is to add the icon/logo in the brands home assistant project, waiting for a review:
> [home-assistant/brands#2575](https://github.com/home-assistant/brands/pull/2575)

Nice work. Thanks.

**Comment by kongo09** [comment]
> I modified the structure of the repo to allow it to be added in hacs.

This doesn't work yet. When I add it as Custom Repository to HACS, it complains: `Repository structure for v0.8 is not compliant`.

I'm not an expert, but could it be that you're missing some keys in the manifest file?
https://hacs.xyz/docs/publish/integration

**Comment by kongo09** [comment]
Ah, I think it picks up your v0.8 release from Nov last year. Maybe you can do a v0.9?

**Comment by slashback100** [comment]
The manifest is fine.
But one of the pre-requisit for HACS is to have the logo & icon in the brand repo, and this step in ongoing (see my comment https://github.com/slashback100/presence_simulation/issues/8#issuecomment-840804173)

**Comment by kongo09** [comment]
I have forked and created a new release. That's what makes it work. Logo is not needed.

**Comment by slashback100** [comment]
Pull request to add the integration in HACS
https://github.com/hacs/default/pull/946

**Comment by kongo09** [comment]
You can already add it as a custom repository, but it needs a current release for that. Obviously, for being listed in HACS as well 😎

**Comment by gjelsoe** [comment]
I've got it listed in HACS now.

**Comment by gjelsoe** [comment]
> Pull request to add the integration in HACS
> [hacs/default#946](https://github.com/hacs/default/pull/946)

Seems to be a issue with manifest.json "version": 1, -> "version": "1", they want a string.

**Comment by kongo09** [comment]
Installation as custom repository works fine now.

**Comment by slashback100** [comment]
FYI it also integrated in HACS repository now

**Comment by gjelsoe** [comment]
Great work... Thanks.
