### ISSUE TITLE
Previous state is not correctly restored after HA reboot

### ISSUE THREAD

**Issue by ds7771** [slashback100/presence_simulation#81]
After HA reboot, the logs show that the code routine is correctly checking whether Presence Simulation state was previously running.  

However previous ‘on’ state is being incorrectly reflected as ‘false’ and therefore Presence Simulation is reverting to ‘off’ after HA reboot.

**Comment by slashback100** [comment]
Fixed in commit [881615a](https://github.com/slashback100/presence_simulation/commit/881615a787997e4d6740951b6d57c59d053f59ca).
This was due to the fact that now the entity name is not directly in States table but is in StatesMeta table.

**Comment by slashback100** [comment]
Fix in [v3.0](https://github.com/slashback100/presence_simulation/releases/tag/v3.0)

**Comment by ds7771** [comment]
Confirmed fixed — thank you!
