### ISSUE TITLE
Does this work with mariadb?

### ISSUE THREAD

**Issue by pdawg17** [slashback100/presence_simulation#82]
It doesn’t seem to work for me but before uninstalling mariadb wanted to check here. Thanks.

**Comment by mvaneijken** [comment]
Yes it works when using MariaDB.

**Comment by pdawg17** [comment]
> Yes it works when using MariaDB.

Ok thanks. I’m asking because I can’t get presence simulation to turn on any lights so trying to eliminate possible reasons. Thanks!
