### ISSUE TITLE
Nested groups

### ISSUE THREAD

**Issue by Eckart0** [slashback100/presence_simulation#85]
Nested groups are apparently not supported at present. I have all lamps of a room in one group and all groups of a floor again in one group. When I enter the in "persence_simulation", it is not resolved.

Can this be changed or do I have to create my own groups only for the presence simulation?

Greetings, Eckart

**Comment by slashback100** [comment]
Nested groups management is supposed to work.
Can you put your log in level debug and send me the log?

**Comment by slashback100** [comment]
FYI I tested by 
- Creating a light group `light.group_1` containing 2 lights
- Creating a second light group `light.group_2` containing 1 light and  `light.group_1`
- Launching the simulation on `light.group_2`
Simulation runs correctly on the 3 lights.

**Comment by Eckart0** [comment]
Hi, I will test it again and write a debug log. I’m at home again on Sunday.Thanks, Eckart--Eckart SeveringAm 27.04.2023 um 11:20 schrieb slashback100 ***@***.***>:﻿
FYI I tested by

Creating a light group light.group_1 containing 2 lights
Creating a second light group light.group_2 containing 1 light and  light.group_1
Launching the simulation on light.group_2
Simulation runs correctly on the 3 lights.

**Comment by slashback100** [comment]
Any news @Eckart0?
