### ISSUE TITLE
switch.presence_simulation is unavailable after install

### ISSUE THREAD

**Issue by AndLindemann** [slashback100/presence_simulation#89]
I installed the integration from HACS with fairly simple settings (just one light entity, otherwise all settings as they came by default).
But the switch.presence_simulation entity is always unavailable, so it can't be toggled on or off. So it doesn't really work at all.
Any idea what the issue is here? HA version 2023.6.3.

When I'm installing the integration, the following error appears in the HA protocol and also does so on every HA restart afterwards:
<img width="390" alt="image" src="https://github.com/slashback100/presence_simulation/assets/4157845/0477f845-8c80-41b1-9798-b6ecdd4e8afb">

Config:

<img width="1150" alt="image" src="https://github.com/slashback100/presence_simulation/assets/4157845/8891d8e6-da50-4d15-9705-08ccdb27cce4">

<img width="565" alt="image" src="https://github.com/slashback100/presence_simulation/assets/4157845/7a2022c4-855e-4b84-8c8e-f1422805f184">

<img width="387" alt="image" src="https://github.com/slashback100/presence_simulation/assets/4157845/eb53fa66-0a2d-4ecd-adf8-5b7527cf562a">

**Comment by slashback100** [comment]
Could you activate the log, try to activate the Switch and send me the log?

**Comment by slashback100** [comment]
There is an error icon next to the switch entity, could you also provide me the installation log?

**Comment by ksga** [comment]
Same issue - reboot fixed it :)

**Comment by AndLindemann** [comment]
The switch starts to work and is available once I used the service to switch the integration on for the first time. After that the switch started working as well.
I'm still seeing that :0.0 Script error in the log though on every HA restart if the integration is installed. Wasn't able to get any further log output from it though. Turning on debug logging in the integration doesn't seem to help with that.
