### ISSUE TITLE
Please make it work for light groups

### ISSUE THREAD

**Issue by kongo09** [slashback100/presence_simulation#9]
![Screenshot_20210512-232643_Home Assistant](https://user-images.githubusercontent.com/640121/118046797-1f73d900-b37a-11eb-87b9-915e48ac0541.jpg)

It currently doesn't seem to work with light groups.

**Comment by slashback100** [comment]
I didn't know about light groups. 
I will take a look at it.

**Comment by slashback100** [comment]
Done
