### ISSUE TITLE
No Lights On last Friday...What about next Friday?

### ISSUE THREAD

**Issue by t34wrj** [slashback100/presence_simulation#90]
If I was not home last Friday evening, and therefore no lights were on, what approach will presence_simulation take to the next Friday in respect of those lights that I have selected?

**Comment by slashback100** [comment]
If you choose to run the simulation with a delta of 7 days, it will not turn your light on or off if you did't turn it on or off the previous Friday. 
2 solutions for you:
- Run the simulation with a delta <> 7
- Create an automation to always turn on the simulation when you are away. That way, your lights could be turned on and off by the simulation the Friday you were gone, and then will be turn on and off the next Friday
