### ISSUE TITLE
Daylight Saving Time

### ISSUE THREAD

**Issue by Bytelink5616** [slashback100/presence_simulation#96]
I noticed that the recorded light activity works well. However when daylight savings starts and ends the lights switch on at strange times like during the day and or later at night depending on which way the clock has moved is there a way to compensate for this anomily.

**Comment by slashback100** [comment]
Sorry I don't understand when you talk about 'daylight savings starts'?

**Comment by Bytelink5616** [comment]
Yes I did not know if it was as simple as adding adjust for DST checkbox and then adding and deleting the offset at the particular time

Ian Robson
Bytelink LLC.
5616 Devon Street
Port Orange, FL 32127
(386) 235-9563  Cell
